id: P004634
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ58530
  title: གསུང་འབུམ། བཀྲ་ཤིས་རྒྱལ་མཚན།
  author: ''
  volumes:
    411bb72cfce5412986b455140fca9fb1:
      image_group_id: I4CZ58744
      title: ''
      volume_number: 1
      total_pages: 439
    c0f2b2cf1f1b4dddbabfb15febb38b00:
      image_group_id: I4CZ58745
      title: ''
      volume_number: 2
      total_pages: 526
    7bf0b05ad26c40cfb4553ea82b320e44:
      image_group_id: I4CZ58746
      title: ''
      volume_number: 3
      total_pages: 536
    ac037cca91014c9da9235137ae9c7925:
      image_group_id: I4CZ58747
      title: ''
      volume_number: 4
      total_pages: 562
    a1e1dc49d158411e9dd22887f1b6b724:
      image_group_id: I4CZ58748
      title: ''
      volume_number: 5
      total_pages: 774
    c768bc51f3cd46ac81445b03dbcbed80:
      image_group_id: I4CZ58749
      title: ''
      volume_number: 6
      total_pages: 643
    c8f12be8ec9d4db4870a9eb8cf8079c1:
      image_group_id: I4CZ58750
      title: ''
      volume_number: 7
      total_pages: 498
    a7e8b5f9283b4309b792ee5ab84a2068:
      image_group_id: I4CZ58751
      title: ''
      volume_number: 8
      total_pages: 770
    b2a12d4c8d784c95a89de11213eb3baf:
      image_group_id: I4CZ58752
      title: ''
      volume_number: 9
      total_pages: 292
    6b90b6c7046e4596b5be066b09eeeea4:
      image_group_id: I4CZ58753
      title: ''
      volume_number: 10
      total_pages: 556
    a2635790532a471197d28fd741edce4c:
      image_group_id: I4CZ58754
      title: ''
      volume_number: 11
      total_pages: 747
    c87026ba26d94f5bb1b9c5c007808bdd:
      image_group_id: I4CZ58755
      title: ''
      volume_number: 12
      total_pages: 544
    563770dd4f4b47e6998cc8ccc6601480:
      image_group_id: I4CZ58756
      title: ''
      volume_number: 13
      total_pages: 508
    704be6eaac8a48fb9e2ac65396af26a0:
      image_group_id: I4CZ58757
      title: ''
      volume_number: 14
      total_pages: 555
    9994d55f990942409d82c3c5ff254345:
      image_group_id: I4CZ58758
      title: ''
      volume_number: 15
      total_pages: 778
    4a11a3bc37bd40b081fff5b6a0cd6e9e:
      image_group_id: I4CZ58759
      title: ''
      volume_number: 16
      total_pages: 738
    c86efe62d9f24d3b929d3ee3a7fed278:
      image_group_id: I4CZ58760
      title: ''
      volume_number: 17
      total_pages: 432
    72eb21f9c5d74cddadf3eef317330304:
      image_group_id: I4CZ58761
      title: ''
      volume_number: 18
      total_pages: 560
